version: "3.8"

services:
  mongo_db:
    container_name: database_container
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_db:/data/db
    networks:
      - app_network

  app:
    build: .
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      GOOGLE_CLIENT_ID: 113220250837-5hnd3vup12nk15sq5050pcgfepj32776.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: asdadasdasdsad
      JWT_SECRET : abcdefghijklmn
      GOOGLE_MAP_API_KEY: AIzaSyCAzgjpFOMCqPpDdaoI-ZPS6ihQygdp0rY
      ADMIN_EMAIL: admin@gmail.com
      ADMIN_PASSWORD: admin123
      ADMIN_HASHED_PASSWORD: $2a$10$a5ySoUUz699BVbsfX7ZRnOtApsE39Cdy7ApyTFQ0TVJYzgKRRUZaW
      ADMIN_JWT_SECRET: abcdefghijklmn
      MONGO_URI: mongodb://mongo_db:27017/codeblue
    depends_on:
      - mongo_db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/nginx
    depends_on:
      - app
    networks:
      - app_network
        
volumes:
  mongo_db: {}

networks:
  app_network:
    driver: bridge